name = "hubla"
author = "bob the builder"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "113fc41f9a2497cf76e78dfd38fe15e1522b0c752b8b6a7afa8f3d03bf73912d"

[versions]
forge = "36.2.20"
minecraft = "1.16.5"
