name = "hubla"
author = "bob the builder"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9df29b19384d9067f42329aa023a84ff3f4c2cca56bad3c6166f0d5d823528a1"

[versions]
forge = "36.2.20"
minecraft = "1.16.5"
