name = "hubla"
author = "bob the builder"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "08ef932026b2c52e201e12509f1e1457d03c2d947427a77b9cd749d8b1678dc5"

[versions]
forge = "36.2.20"
minecraft = "1.16.5"
