name = "hubla"
author = "bob the builder"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e25a2babdd323057242904a7d00696f093ba963372f938964de90e2cf68786b9"

[versions]
forge = "36.2.20"
minecraft = "1.16.5"
