name = "hubla"
author = "bob the builder"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e4ba2f162eaf085dcac079f53cc8bc705cf5e9f078e5e58b69e8d87a7e58487f"

[versions]
forge = "36.2.20"
minecraft = "1.16.5"
