name = "hubla"
author = "bob the builder"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "211111579d41bc049933665d61119c0f3c646c45f5115c5ecd5cb8f2faf82edd"

[versions]
forge = "36.2.20"
minecraft = "1.16.5"
