name = "hubla"
author = "bob the builder"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "efd968caf526e9d0ca937be6b49ed9701f47aefd83850b5943db76762f3d8d80"

[versions]
forge = "36.2.20"
minecraft = "1.16.5"
