name = "hubla"
author = "bob the builder"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "644346fedd28b34508d5cd5eb22314843bcf9b6789bf534b614e8d1795287968"

[versions]
forge = "36.2.20"
minecraft = "1.16.5"
