name = "hubla"
author = "bob the builder"
version = "0.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "398f9ae7f828a70f774f287ebd2ccf09f886dbb650ddac256754fd0ec6818593"

[versions]
forge = "36.2.20"
minecraft = "1.16.5"
