name = "Advanced Peripherals"
filename = "advancedperipherals-1.16.5-0.7.6r.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3566/844/advancedperipherals-1.16.5-0.7.6r.jar"
hash-format = "murmur2"
hash = "3819401593"

[update]
[update.curseforge]
file-id = 3566844
project-id = 431725
