name = "Ars Nouveau"
filename = "ars_nouveau-1.16.5-1.24.12.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3586/196/ars_nouveau-1.16.5-1.24.12.jar"
hash-format = "murmur2"
hash = "1437966363"

[update]
[update.curseforge]
file-id = 3586196
project-id = 401955
