name = "Better End Cities"
filename = "com.netherairtune.endcity-1.0-1.16.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3513/721/com.netherairtune.endcity-1.0-1.16.jar"
hash-format = "murmur2"
hash = "619743658"

[update]
[update.curseforge]
file-id = 3513721
project-id = 543893
