name = "Blood Magic "
filename = "BloodMagic-1.16.4-3.1.7-27.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3568/763/BloodMagic-1.16.4-3.1.7-27.jar"
hash-format = "murmur2"
hash = "2893550765"

[update]
[update.curseforge]
file-id = 3568763
project-id = 224791
