name = "Catalogue"
filename = "catalogue-1.5.0-1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3529/457/catalogue-1.5.0-1.16.5.jar"
hash-format = "murmur2"
hash = "3230509572"

[update]
[update.curseforge]
file-id = 3529457
project-id = 459701
