name = "CC: Tweaked"
filename = "cc-tweaked-1.16.5-1.100.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3587/945/cc-tweaked-1.16.5-1.100.1.jar"
hash-format = "murmur2"
hash = "1111885083"

[update]
[update.curseforge]
file-id = 3587945
project-id = 282001
