name = "CoFH Core"
filename = "cofh_core-1.16.5-1.4.0.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3556/973/cofh_core-1.16.5-1.4.0.6.jar"
hash-format = "murmur2"
hash = "2518958035"

[update]
[update.curseforge]
file-id = 3556973
project-id = 69162
