name = "Common Capabilities"
filename = "CommonCapabilities-1.16.5-2.8.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3482/420/CommonCapabilities-1.16.5-2.8.0.jar"
hash-format = "murmur2"
hash = "3223743797"

[update]
[update.curseforge]
file-id = 3482420
project-id = 247007
