name = "Corail Tombstone"
filename = "tombstone-6.6.3-1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3551/696/tombstone-6.6.3-1.16.5.jar"
hash-format = "murmur2"
hash = "1074669831"

[update]
[update.curseforge]
file-id = 3551696
project-id = 243707
