name = "Create Deco"
filename = "createdeco-1.1.2-1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3503/936/createdeco-1.1.2-1.16.5.jar"
hash-format = "murmur2"
hash = "1002539606"

[update]
[update.curseforge]
file-id = 3503936
project-id = 509285
