name = "Cyclops Core"
filename = "CyclopsCore-1.16.5-1.12.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3517/568/CyclopsCore-1.16.5-1.12.1.jar"
hash-format = "murmur2"
hash = "4031874212"

[update]
[update.curseforge]
file-id = 3517568
project-id = 232758
