name = "'Dustrial Decor"
filename = "DustrialDecor-1.3.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3548/29/DustrialDecor-1.3.0.jar"
hash-format = "murmur2"
hash = "4177250554"

[update]
[update.curseforge]
file-id = 3548029
project-id = 401273
