name = "EnderChests"
filename = "enderchests-1.16-1.7.9.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3562/111/enderchests-1.16-1.7.9.jar"
hash-format = "murmur2"
hash = "892352302"

[update]
[update.curseforge]
file-id = 3562111
project-id = 363535
