name = "Engineer's Decor"
filename = "engineersdecor-1.16.5-1.1.16-b1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3566/177/engineersdecor-1.16.5-1.1.16-b1.jar"
hash-format = "murmur2"
hash = "2252323848"

[update]
[update.curseforge]
file-id = 3566177
project-id = 313866
