name = "Ice and Fire: Dragons"
filename = "iceandfire-2.1.9-1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3441/117/iceandfire-2.1.9-1.16.5.jar"
hash-format = "murmur2"
hash = "962581471"

[update]
[update.curseforge]
file-id = 3441117
project-id = 264231
