name = "Immersive Posts"
filename = "immersiveposts-1.16.5-4.2.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3455/488/immersiveposts-1.16.5-4.2.2.jar"
hash-format = "murmur2"
hash = "2363281232"

[update]
[update.curseforge]
file-id = 3455488
project-id = 314645
