name = "Integrated Tunnels"
filename = "IntegratedTunnels-1.16.5-1.8.9.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3546/791/IntegratedTunnels-1.16.5-1.8.9.jar"
hash-format = "murmur2"
hash = "1498735082"

[update]
[update.curseforge]
file-id = 3546791
project-id = 251389
