name = "Integrated Dynamics"
filename = "IntegratedDynamics-1.16.5-1.10.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3546/747/IntegratedDynamics-1.16.5-1.10.6.jar"
hash-format = "murmur2"
hash = "1290848987"

[update]
[update.curseforge]
file-id = 3546747
project-id = 236307
