name = "Inventory Essentials"
filename = "InventoryEssentials_1.16.5-2.3.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3332/381/InventoryEssentials_1.16.5-2.3.2.jar"
hash-format = "murmur2"
hash = "4171514000"

[update]
[update.curseforge]
file-id = 3332381
project-id = 368825
