name = "Macaw's Roofs - Biomes O' Plenty"
filename = "macawsroofsbop-1.16.5-1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3571/604/macawsroofsbop-1.16.5-1.0.jar"
hash-format = "murmur2"
hash = "3832392201"

[update]
[update.curseforge]
file-id = 3571604
project-id = 558344
