name = "[Fabric/Forge] Market Crates 1.16/1.17/1.18"
filename = "MarketCrates-1.16.4-35.1.4-v1.1-universal.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3207/286/MarketCrates-1.16.4-35.1.4-v1.1-universal.jar"
hash-format = "murmur2"
hash = "203927379"

[update]
[update.curseforge]
file-id = 3207286
project-id = 443591
