name = "RoadRunner"
filename = "RoadRunner-mc1.16.5-1.4.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3565/489/RoadRunner-mc1.16.5-1.4.0.jar"
hash-format = "murmur2"
hash = "2454826495"

[update]
[update.curseforge]
file-id = 3565489
project-id = 529754
