name = "Magnesium"
filename = "magnesium-1.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3526/76/magnesium-1.5.jar"
hash-format = "murmur2"
hash = "2419099626"

[update]
[update.curseforge]
file-id = 3526076
project-id = 532724
