name = "Spice of Life: Carrot Edition"
filename = "SoL-Carrot-1.16.5-1.10.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3420/107/SoL-Carrot-1.16.5-1.10.1.jar"
hash-format = "murmur2"
hash = "2227292078"

[update]
[update.curseforge]
file-id = 3420107
project-id = 277616
