name = "Supplementaries"
filename = "supplementaries-1.16.5-0.18.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3583/790/supplementaries-1.16.5-0.18.0.jar"
hash-format = "murmur2"
hash = "3846467080"

[update]
[update.curseforge]
file-id = 3583790
project-id = 412082
