name = "Thermal Foundation"
filename = "thermal_foundation-1.16.5-1.4.1.7.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3556/953/thermal_foundation-1.16.5-1.4.1.7.jar"
hash-format = "murmur2"
hash = "3619289507"

[update]
[update.curseforge]
file-id = 3556953
project-id = 222880
